# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
rtl: false # true, false (default) # turns direction of the page into right to left for RTL languages
title: "Brett Wallace"
title_separator: "-"
subtitle: "artist and filmmaker"
name: "Brett Wallace"
description: "artist and filmmaker, labor, economy, future of work"
url: "https://brettwallace.github.io"
baseurl: "" # e.g. "/brettwallace.com/"
repository: "brettwallace/brettwallace.github.io"
teaser: "/assets/images/american-union-film-2021-001-web.jpg"
logo: "/assets/images/american-union-film-2021-001-web.jpg"
masthead_title: null # overrides the website title displayed in the masthead, use "" for no title
breadcrumbs: false # true, false (default)
words_per_minute: 200
enable_copy_code_button: false # true, false (default)
copyright: "Brett Wallace"
copyright_url: "https://brettwallace.github.io"

comments:
  provider: false
  disqus:
    shortname: ""
  discourse:
    server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
  giscus:
    repo_id: ""
    category_name: ""
    category_id: ""
    discussion_term: "pathname"
    reactions_enabled: '1'
    theme: "light"
    strict: 0
    input_position: "bottom"
    emit_metadata: 0
    lang: "en"
    lazy: false
  staticman:
    branch: "master"
    endpoint: ""

reCaptcha:
  siteKey: ""
  secret: ""

atom_feed:
  path: "" # blank (default) uses feed.xml
  hide: false

search: true
search_full_content: false
search_provider: lunr # lunr (default), algolia, google

lunr:
  search_within_pages: false

algolia:
  application_id: ""
  index_name: ""
  search_only_api_key: ""
  powered_by: true

google:
  search_engine_id: ""
  instant_search: false

# SEO Related
google_site_verification: ""
bing_site_verification: ""
naver_site_verification: ""
yandex_site_verification: ""
baidu_site_verification: ""

# Social Sharing
twitter:
  username: ""
facebook:
  username: ""
  app_id: ""
  publisher: ""
og_image: "" # Open Graph/Twitter default site image

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: "Person" # Person or Organization (defaults to Person)
  name: "Brett Wallace" # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/brettwallace"
    - "https://github.com/brettwallace"
    - "https://instagram.com/brettwallacenyc"
    - "https://brettwallace.com"
    # Add more links as needed

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: ""
    anonymize_ip: false

# Site Author
author:
  name: "Brett Wallace"
  avatar: # # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "I am an **artist** and **filmmaker**"
  location: "upstate New York, USA"
  email: "brett@brettwallace.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your.brett@brettwallace.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://brettwallace.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/brettwallace"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brettwallace"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/brettwallacenyc"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/brettwallace"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: ""
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brettwallace"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: ""
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: ""
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/brettwallacenyc"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: "" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
pagination:
  # enabled: true # Set enabled to true to use paginate v2
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
