title: brettwallace.com
logo
description: artist and filmmaker
#show_downloads: true
theme: minimal-mistakes-jekyll

google_analytics:
plugins:
  - pagemaster

works:
  work:
    output: true
    source: works.csv
    id_key: url
    layout:  works
    sort_by: year
    
